services:
  - type: web
    name: echolens-ai
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false # This means you'll need to set this manually in the Render dashboard
    healthCheckPath: /api/status 